### Python For Everyone - Exploring Data In Python 3.
### By Prof. Charles R. Severance

1. Introduction

Write a program that uses a print function to say 'hello world'.

In [47]:
print("hello world")

hello world


2.2 Variables, expressions and statements

+ Write a program that uses input to prompt a user for their name and then welcomes them.

In [49]:
name = input("Enter your name: ")
print("Hello "+ name)

Enter your name: Python
Hello Python


2.3 Variables, expressions and statements

+ Write a program to prompt the user for hours and rate per hour using input to compute gross pay.

+ Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25).

+ You should use input to read a string and float() to convert the string to a number. 

+ Do not worry about error checking or bad user data.

In [15]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")
print("Pay:",float(hrs) * float(rate))

Enter Hours:35
Enter Rate:2.75
Pay: 96.25


3.1 Conditional Execution

+ Write a program to prompt the user for hours and rate per hour using input to compute gross pay.

+ Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours.

+ Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75).

+ You should use input to read a string and float() to convert the string to a number.

+ Do not worry about error checking the user input - assume the user types numbers properly.

In [14]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")

h = float(hrs)
r = float(rate)
pay = 0

if h < 40:
    pay = h * r
    print(pay)
else:
    lvlTwoHrs = h - 40.0
    lvlTwoRate = r * 1.5
    lvlOnePay = 40.0 * r
    lvlTwoPay = lvlTwoHrs * lvlTwoRate
    pay = lvlOnePay + lvlTwoPay
    print(pay)

Enter Hours:45
Enter Rate:10.50
498.75


3.2 Conditional Execution
+ Write a program to prompt for a score between 0.0 and 1.0. 
+ If the score is out of range, print an error. 
+ If the score is between 0.0 and 1.0, print a grade using the following table:
+ Score Grade

```
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
```
+ If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [50]:
score = input("Enter Score: ")

rscore = float(score)

if rscore < 0.0 or rscore > 1.0:
    print('Out of range')
elif rscore >= 0.9:
    print('A')
elif rscore >= 0.8:
    print('B')
elif rscore >= 0.7:
    print('C')
elif rscore >= 0.6:
    print('D')
elif rscore > 0.0 and rscore < 0.6:
    print('F')

Enter Score: 0.85
B


4.6 Functions

+ Write a program to prompt the user for hours and rate per hour using input to compute gross pay.
+ Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. 
+ Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. 

+ The function should return a value. 

+ Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). 
+ You should use input to read a string and float() to convert the string to a number. 
+ Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. 
+ Do not name your variable sum or use the sum() function.

In [51]:
def computepay(hrs, rate):
    h = float(hrs)
    r = float(rate) 
    pay = 0

    if h <= 40.0:
        pay = h * r
    elif h > 40.0:
        pay1 = 40.0 * r
        pay2 = float(h - 40.0) * float(r * 1.5)
        pay = pay1 + pay2

    return pay

hrs = input("Enter Hours:")
rate = input("Enter Rate:")

p = computepay(hrs, rate)
print("Pay", p)

Enter Hours:45
Enter Rate:10.50
Pay 498.75


5.2 Loops and Iterations

+ Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. 
+ Once 'done' is entered, print out the largest and smallest of the numbers. 
+ If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. 
+ Enter 7, 2, bob, 10, and 4 and match the output below.

```
Output:

1. Invalid input
2. Maximum is 10
3. Minimum is 2

```

In [52]:
largest = None
smallest = None

userList = []

while True:
    num = input("Enter a number: ")
    
    if num == "done":
        largest = max(userList)
        smallest = min(userList)
        print('Maximum is', largest)
        print('Minimum is', smallest)
        break
    try:
        intNum = int(num)
    except:
        print('Invalid input')
        
    userList.append(intNum)

Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2


6.5 Strings

+ Write code using find() and string slicing (see section 6.10) to extract the number at the end of the line below. 
+ Convert the extracted value to a floating point number and print it out.

In [53]:
text = "X-DSPAM-Confidence:    0.8475"

seek = text.find('0')
numVal = float(text[seek:])
print(numVal)

0.8475


7.2 Files

+ Write a program that prompts for a file name, then opens that file and reads through the file, looking for lines of the form:
X-DSPAM-Confidence:    0.8475
+ Count these lines and extract the floating point values from each of the lines and compute the average of those values and produce an output as shown below. 

```
Output:

Average spam confidence: 0.7507185185185187
```

+ Do not use the sum() function or a variable named sum in your solution.
+ You can download the sample data at http://www.py4e.com/code3/mbox-short.txt when you are testing below enter mbox-short.txt as the file name.

In [56]:
numList = []
total = 0.0

fname = input("Enter file name: ")

if len(fname) < 1:
    fname = "../data/mbox-short.txt"

fh = open(fname)

for line in fh:
    if not line.startswith("X-DSPAM-Confidence:"):
        continue
    seek = line.find('0')
    lineNum = line[seek:]
    lineNum = float(lineNum)
    numList.append(lineNum)

for num in numList:
    total = num + total

count = float(len(numList))
    
average = total / count
print("Average spam confidence:",average)

Enter file name: 
Average spam confidence: 0.7507185185185187


8.4 Lists

+ Open the file romeo.txt and read it line by line. 
+ For each line, split the line into a list of words using the split() method. 
+ The program should build a list of words. For each word on each line check to see if the word is already in the list and if not append it to the list. 
+ When the program completes, sort and print the resulting words in python sort() order as shown in the desired output.
+ You can download the sample data at http://www.py4e.com/code3/romeo.txt

In [58]:
wlist = []

fname = input("Enter file name: ")

if len(fname) < 1:
    fname = "../data/romeo.txt"
    
flines = open(fname)

for line in flines:
    words = line.split()
    for word in words:
        if word not in wlist:
            wlist.append(word)
wlist.sort()
print(wlist)

Enter file name: 
['Arise', 'But', 'It', 'Juliet', 'Who', 'already', 'and', 'breaks', 'east', 'envious', 'fair', 'grief', 'is', 'kill', 'light', 'moon', 'pale', 'sick', 'soft', 'sun', 'the', 'through', 'what', 'window', 'with', 'yonder']


9.4 Dictionaries

+ Write a program to read through the mbox-short.txt and figure out who has sent the greatest number of mail messages. 
+ The program looks for 'From ' lines and takes the second word of those lines as the person who sent the mail. 
+ The program creates a Python dictionary that maps the sender's mail address to a count of the number of times they appear in the file. 
+ After the dictionary is produced, the program reads through the dictionary using a maximum loop to find the most prolific committer.

In [55]:
name = input("Enter file:")

if len(name) < 1:
    name = "../data/mbox-short.txt"
handle = open(name)

mailDict = {}

for line in handle:
    if line.startswith('From '):
        testLine = line.split()
        mailDict[testLine[1]] = testLine[4]

largest = 0

for keys in mailDict:
    mailNum = int(mailDict[keys])
    if mailNum > largest:
        largest = mailNum
        print(mailDict[keys])

print(mailDict)

Enter file:
4
{'stephen.marquard@uct.ac.za': '4', 'louis@media.berkeley.edu': '3', 'zqian@umich.edu': '4', 'rjlowe@iupui.edu': '4', 'cwen@iupui.edu': '3', 'gsilver@umich.edu': '4', 'wagnermr@iupui.edu': '4', 'antranig@caret.cam.ac.uk': '4', 'gopal.ramasammycook@gmail.com': '4', 'david.horwitz@uct.ac.za': '4', 'ray@media.berkeley.edu': '3'}


10.2 Tuples

+ Write a program to read through the mbox-short.txt and figure out the distribution by hour of the day for each of the messages. 
+ You can pull the hour out from the 'From ' line by finding the time and then splitting the string a second time using a colon.
```
From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
```
+ Once you have accumulated the counts for each hour, print out the counts, sorted by hour as shown below.

In [60]:
import re

pattern = r'\d{1,2}:\d{1,2}'
timeTuple = []

name = input("Enter file:")
if len(name) < 1:
    name = "../data/mbox-short.txt"
    
handle = open(name)
for line in handle:
    if line.startswith('From'):
        matches = re.findall(pattern, line)
        for match in matches:
           time1 = match[:2]
           time2 = match[3:5]
           timeTuple.append((time1, time2))
           timeTuple = sorted(timeTuple)
           
for (x, y) in timeTuple:
    print(x, y)

Enter file:
04 07
04 33
04 49
06 08
07 02
09 05
09 14
10 04
10 17
10 38
11 10
11 11
11 11
11 12
11 35
11 37
14 50
15 03
15 46
16 10
16 23
16 29
16 34
17 07
17 18
18 10
19 51


11. Regular Expressions

+ In this assignment you will read through and parse a file with text and numbers. 
+ You will extract all the numbers in the file and compute the sum of the numbers.
+ There are 106 values and the sum ends with 973

In [61]:
import re
list = []
# file url : : http://py4e-data.dr-chuck.net/regex_sum_1798206.txt
fileHandle = open('regex_sum.txt')
for line in fileHandle:
    targetString = re.findall('[0-9]+',line)
    for num in targetString:
        num = int(num)
        list.append(num)
print(f'There are {len(list)} values with a sum of {sum(list)}')

There are 106 values with a sum of 508973


12.1 Networked Applications

+ You are to retrieve the following document using the HTTP protocol in a way that you can examine the HTTP Response headers.

http://data.pr4e.org/intro-short.txt

In [62]:
import urllib.request, urllib.parse, urllib.error

f_handle = urllib.request.urlopen('http://data.pr4e.org/intro-short.txt')

f_headers = f_handle.getheaders()

print(f'[Headers] : {f_headers}')
 
def read_fhandle(f_handle):
    print('\n========== Reading File ==========')
    for line in f_handle:
        print(line.decode().strip())
    print('========== Done Reading File ==========')
    
read_fhandle(f_handle)

[Headers] : [('Date', 'Mon, 29 May 2023 21:41:43 GMT'), ('Server', 'Apache/2.4.18 (Ubuntu)'), ('Last-Modified', 'Sat, 13 May 2017 11:22:22 GMT'), ('ETag', '"1d3-54f6609240717"'), ('Accept-Ranges', 'bytes'), ('Content-Length', '467'), ('Cache-Control', 'max-age=0, no-cache, no-store, must-revalidate'), ('Pragma', 'no-cache'), ('Expires', 'Wed, 11 Jan 1984 05:00:00 GMT'), ('Connection', 'close'), ('Content-Type', 'text/plain')]

========== Reading File ==========
Why should you learn to write programs?

Writing programs (or programming) is a very creative
and rewarding activity.  You can write programs for
many reasons, ranging from making your living to solving
a difficult data analysis problem to having fun to helping
someone else solve a problem.  This book assumes that
everyone needs to know how to program, and that once
you know how to program you will figure out what you want
to do with your newfound skills.
========== Done Reading File ==========


12.2 Scraping Numbers from HTML using BeautifulSoup 

+ The program will use urllib to read the HTML from the data files below, and parse the data, extracting numbers and compute the sum of the numbers in the file.

+ We provide two files for this assignment. One is a sample file where we give you the sum for your testing and the other is the actual data you need to process for the assignment.

In [63]:
# Sample data = http://py4e-data.dr-chuck.net/comments_42.html (Sum=2553)
# Actual data = http://py4e-data.dr-chuck.net/comments_1798208.html (Sum ends with 2)
        
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl

# handles SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = 'http://py4e-data.dr-chuck.net/comments_1798208.html'

# run loop on the response of urlopen if content is sizeable
html = urllib.request.urlopen(url, context=ctx).read()
soup = BeautifulSoup(html,'html.parser')

# tags = soup('td')

tags = soup.find_all(class_='comments')

tags_sum = []

for tag in tags:
    comment_num = int(tag.text)
    tags_sum.append(comment_num)

print(f'Sum = {sum(tags_sum)}')

Sum = 2502


12.3 Following Links in Python

+ The program will use urllib to read the HTML from the data files below.

+ Extract the href= vaues from the anchor tags, 

+ scan for a tag that is in a particular position relative to the first name in the list

+ follow that link and repeat the process a number of times and report the last name you find.

+ We provide two files for this assignment. One is a sample file where we give you the name for your testing and the other is the actual data you need to process for the assignment

+ Sample problem: Start at http://py4e-data.dr-chuck.net/known_by_Fikret.html
+ Sequence of names: Fikret Montgomery Mhairade Butchi Anayah
    Last name in sequence: Anayah
+ Actual problem: Start at: http://py4e-data.dr-chuck.net/known_by_Zoha.html

In [16]:
# sample: http://py4e-data.dr-chuck.net/known_by_Fikret.html
# Find the link at position 3 (the first name is 1).
# Follow that link. Repeat this process 4 times. 
# The answer is the last name that you retrieve.

# Find the link at position 18 (the first name is 1). 
# Follow that link. Repeat this process 7 times. 
# The answer is the last name that you retrieve.


import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl

# handle SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE


# url = 'http://py4e-data.dr-chuck.net/known_by_Fikret.html'
url = 'http://py4e-data.dr-chuck.net/known_by_Zoha.html'

# count = int(input('Enter count : '))
# line = int(input('Enter position'))

repeat = 4
position = 3

for i in range(repeat):
    html = urllib.request.urlopen(url, context=ctx).read()
    soup = BeautifulSoup(html, 'html.parser')
    tags = soup('a')
    count = 0
    for tag in tags:
        count = count + 1

        if count > position:
            break
        url = tag.get('href', None)
        name = tag.contents[0]

print(name)

Fezaan


Extracting Data from XML

+ The program will prompt for a URL. 
+ Read the XML data from that URL using urllib.
+ Parse and extract the comment counts from the XML data, compute the sum of the numbers in the file.

In [64]:
# Sample data: http://py4e-data.dr-chuck.net/comments_42.xml (Sum=2553)
# Actual data: http://py4e-data.dr-chuck.net/comments_1798210.xml (Sum ends with 69)

import urllib.request, urllib.parse, urllib.error
import xml.etree.ElementTree as ET
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = 'http://py4e-data.dr-chuck.net/comments_1798210.xml'

xml = urllib.request.urlopen(url, context=ctx).read()

tree = ET.fromstring(xml)

comments = tree.findall('comments/comment')
comment_list = []


for comment in comments:
    count = comment.find('count').text
    comment_list.append(int(count))
    
print(f'Sum = {sum(comment_list)}')

Sum = 2069


Extracting Data from JSON

+ The program will prompt for a URL
+ Read the JSON data from that URL using urllib and then parse and extract the comment counts from the JSON data
+ Compute the sum of the numbers in the file and enter the sum below:

In [65]:
# Sample data: http://py4e-data.dr-chuck.net/comments_42.json (Sum=2553)
# Actual data: http://py4e-data.dr-chuck.net/comments_1798211.json (Sum ends with 21)

import urllib.request, urllib.parse, urllib.error
import json
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = 'http://py4e-data.dr-chuck.net/comments_1798211.json'

json_data = urllib.request.urlopen(url, context=ctx).read()

data = json.loads(json_data)

comment_list = []


for comment in data['comments']:
    count = comment['count']
    comment_list.append(int(count))
    
print(f'Sum = {sum(comment_list)}')


Sum = 2121


Databases

+ Using SQLITE browser create a database called 'Ages' that has ```name``` and ```age``` columns

```
CREATE TABLE Ages ( 
  name VARCHAR(128), 
  age INTEGER
)
```

+ Make sure table is empty and insert the rows below.
```
DELETE FROM Ages;
INSERT INTO Ages (name, age) VALUES ('Fendi', 13);
INSERT INTO Ages (name, age) VALUES ('Levi', 24);
INSERT INTO Ages (name, age) VALUES ('Joojo', 22);
INSERT INTO Ages (name, age) VALUES ('Cassieleigh', 35);
INSERT INTO Ages (name, age) VALUES ('Remigiusz', 40);
```

+ Get list of concatenated names and ages in the hexadecimal representation

```
SELECT hex(name || age) AS X FROM Ages ORDER BY X
```

Answer = 4361737369656C656967683335

| Hex |
|---|
| 4361737369656C656967683335 |
| 46656E64693133 |
| 4A6F6F6A6F3232 |
| 4C6576693234 | 
| 52656D69676975737A3430 |


Counting Organisations
+ Read mailbox data from a file (mbox.txt) and count the number of email messages per organization(domain name of email address)

+ Create a database table ```Counts``` that contains a column for the organisation and a column for the frequency.

+ Call the top 10 organisations from the database

In [18]:
import sqlite3
import re

db_connection = sqlite3.connect('emaildb.sqlite')
db_cursor = db_connection.cursor()

db_cursor.execute(
    '''
    DROP TABLE IF EXISTS Counts
    '''
)

db_cursor.execute(
    '''
    CREATE TABLE Counts (org TEXT, count INTEGER)
    '''
)

file_name = '../data/mbox.txt'
file_handle = open(file_name)

target_pattern = r"(?<=@)[^.]+(?:\.[^.]+)+(?=$|\s)"

mail_dict = dict()

for line in file_handle:
    if not line.startswith('From: '): 
        continue
    word_array = line.split()
    email = word_array[1]
    match = re.findall(target_pattern, email)
    match = match[0]
    mail_dict[match] = mail_dict.get(match, 0) + 1

for org, count in mail_dict.items():
    db_cursor.execute(
    '''
    INSERT INTO Counts (org, count) VALUES (?,?)
    ''', (org, count))

db_connection.commit()

topTenOrgs = 'SELECT org, count FROM Counts ORDER BY count DESC'

for row in db_cursor.execute(topTenOrgs):
    print(str(row[0]), row[1])
    
db_connection.close()

iupui.edu 536
umich.edu 491
indiana.edu 178
caret.cam.ac.uk 157
vt.edu 110
uct.ac.za 96
media.berkeley.edu 56
ufp.pt 28
gmail.com 25
et.gatech.edu 17
txstate.edu 17
whitman.edu 17
lancaster.ac.uk 14
bu.edu 14
stanford.edu 12
unicon.net 9
loi.nl 9
rsmart.com 8
ucdavis.edu 1
fhda.edu 1
utoronto.ca 1


Multi-Table Database - Tracks

This application will read an iTunes export file in XML and produce a properly normalized database.

In [87]:
import xml.etree.ElementTree as ET
import sqlite3
import os

db_connection = sqlite3.connect('trackdb.sqlite')
db_cursor = db_connection.cursor()

db_cursor.executescript('''
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Track;

CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);

CREATE TABLE Genre (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    genre_id  INTEGER,
    album_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
''')


# file_name = input('Enter file name: ')
# if ( len(file_name) < 1 ) : file_name = '../data/Library.xml'

file_name = '../data/Library.xml'

# if not os.path.exists(file_name):
#     raise FileNotFoundError(f"File '{file_name}' does not exist")

file_handle = open(file_name)
xml_tree = ET.parse(file_handle)

all = xml_tree.findall('dict/dict/dict')
print('Dict count:', len(all))


for entry in all:
    if ( lookup(entry, 'Track ID') is None ) : continue

    name = lookup(entry, 'Name')
    artist = lookup(entry, 'Artist')
    genre = lookup(entry, 'Genre')
    album = lookup(entry, 'Album')
    count = lookup(entry, 'Play Count')
    rating = lookup(entry, 'Rating')
    length = lookup(entry, 'Total Time')

    if name is None or genre is None or artist is None or album is None : 
        continue

#     print(name, artist, genre, album, count, rating, length)

    db_cursor.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', ( artist, ) )
    db_cursor.execute('SELECT id FROM Artist WHERE name = ? ', (artist, ))
    artist_id = db_cursor.fetchone()[0]
    
    db_cursor.execute('''INSERT OR IGNORE INTO Genre (name) 
        VALUES ( ? )''', ( genre, ) )
    db_cursor.execute('SELECT id FROM Genre WHERE name = ? ', (genre, ))
    genre_id = db_cursor.fetchone()[0]

    db_cursor.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', ( album, artist_id ) )
    db_cursor.execute('SELECT id FROM Album WHERE title = ? ', (album, ))
    album_id = db_cursor.fetchone()[0]

    db_cursor.execute('''INSERT OR REPLACE INTO Track
        (title, album_id, genre_id, len, rating, count) 
        VALUES ( ?, ?, ?, ?, ?, ? )''', 
        ( name, genre_id, album_id, length, rating, count ) )

    db_connection.commit()

Dict count: 404
